# Canonical build, validation, integration-test, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-python.awk
DIST_FILTER := $(DIST_DIR)/doxygen-python.awk
DIST_CHECKSUM := $(DIST_FILTER).sha256
AWK_BIN ?= awk
INTEGRATION_CONFIG := tests/doxygen/Doxyfile
INTEGRATION_OUT := tests/doxygen/out
DOXYGEN_PYTHON_FILTER ?= $(SOURCE_FILTER)

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build checksums clean integration-clean test test-source test-dist test-doxygen

all: build

## Build the exact consumer artifact with immutable provenance metadata.
build: $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_PYTHON_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$(DIST_FILTER).tmp"
	chmod 0755 "$(DIST_FILTER).tmp"
	mv "$(DIST_FILTER).tmp" "$(DIST_FILTER)"

## Run the semantic regression suite against maintained source and consumer output.
test: test-source test-dist

## Run the semantic regression suite against the maintained source file.
test-source:
	DOXYGEN_PYTHON_FILTER="$(SOURCE_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

## Build and run the semantic suite against the exact consumer artifact.
test-dist: build
	test "$$(head -n 1 "$(DIST_FILTER)")" = '#!/usr/bin/awk -f'
	grep -Fxq '# Generated by make build. Do not edit directly.' "$(DIST_FILTER)"
	grep -Fxq '# Source files: $(SOURCE_FILTER)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_PYTHON_VERSION=$(VERSION)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_PYTHON_BUILD_DATE=$(BUILD_DATE)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_PYTHON_BUILD_COMMIT=$(BUILD_COMMIT)' "$(DIST_FILTER)"
	DOXYGEN_PYTHON_FILTER="$(DIST_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

## Exercise one focused Python fixture through Doxygen with the selected filter.
test-doxygen:
	@test -f "$(DOXYGEN_PYTHON_FILTER)" || { printf '%s\n' 'Missing Python Doxygen filter' >&2; exit 1; }
	@command -v doxygen >/dev/null 2>&1 || { printf '%s\n' 'doxygen is required for make test-doxygen' >&2; exit 1; }
	$(MAKE) --no-print-directory integration-clean
	AWK_BIN="$(AWK_BIN)" DOXYGEN_PYTHON_FILTER="$(abspath $(DOXYGEN_PYTHON_FILTER))" doxygen "$(INTEGRATION_CONFIG)"
	grep -R -q 'Normalize a supplied value' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Value to normalize' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'The canonical normalized value' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'ValueError' "$(INTEGRATION_OUT)/xml"

## Generate the SHA-256 checksum for the exact consumer artifact.
checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_FILTER))" >"$(notdir $(DIST_CHECKSUM))"

integration-clean:
	rm -rf "$(INTEGRATION_OUT)"

clean: integration-clean
	rm -rf "$(DIST_DIR)" doc/reference
