# Canonical build and test entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-python.awk
DIST_FILTER := $(DIST_DIR)/doxygen-python.awk
DIST_CHECKSUM := $(DIST_FILTER).sha256
AWK_BIN ?= awk
VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build checksums clean test test-source test-dist

all: build

build: $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_PYTHON_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$(DIST_FILTER).tmp"
	chmod 0755 "$(DIST_FILTER).tmp"
	mv "$(DIST_FILTER).tmp" "$(DIST_FILTER)"

test: test-source test-dist

test-source:
	DOXYGEN_PYTHON_FILTER="$(SOURCE_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

test-dist: build
	test "$$(head -n 1 "$(DIST_FILTER)")" = '#!/usr/bin/awk -f'
	grep -Fq '# DOXYGEN_PYTHON_VERSION=' "$(DIST_FILTER)"
	grep -Fq '# DOXYGEN_PYTHON_BUILD_DATE=' "$(DIST_FILTER)"
	grep -Fq '# DOXYGEN_PYTHON_BUILD_COMMIT=' "$(DIST_FILTER)"
	DOXYGEN_PYTHON_FILTER="$(DIST_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_FILTER))" >"$(notdir $(DIST_CHECKSUM))"

clean:
	rm -rf "$(DIST_DIR)" doc/reference
