# Canonical build, validation, documentation, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-python.awk
AWK_SOURCES := $(SOURCE_FILTER)
DIST_DEV_FILTER := $(DIST_DIR)/doxygen-python.dev.awk
DIST_FILTER := $(DIST_DIR)/doxygen-python.awk
DIST_MIN_FILTER := $(DIST_DIR)/doxygen-python.min.awk
DIST_FILTERS := $(DIST_DEV_FILTER) $(DIST_FILTER) $(DIST_MIN_FILTER)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_FILTERS))
AWK_BIN ?= awk
INTEGRATION_CONFIG := tests/doxygen/Doxyfile
INTEGRATION_OUT := tests/doxygen/out
DOXYGEN_PYTHON_FILTER ?= $(SOURCE_FILTER)

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
DOCS_MANIFEST := dependencies-docs.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.10
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := acbe79d39ab8cbbf906bd864d410ba7a223ba6f09501c02a409b8d3aa8740462
AWK_MINIFIER := $(VENDOR_DIR)/awk-minifier.awk
AWK_MINIFIER_VERSION := 0.2.4
VENDOR_AWK_FILTER := $(VENDOR_DIR)/doxygen-awk.awk
VENDOR_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
ADR_DIR := doc/adr
ADR_INDEX_FILE := $(ADR_DIR)/README.md
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
REFERENCE_DOC_DIR := doc/reference
AWK_DOXYGEN_FILTER ?= $(VENDOR_AWK_FILTER)
BASH_DOXYGEN_FILTER ?= $(VENDOR_BASH_FILTER)

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: adr-index all build check checksums clean deps deps-check deps-docs deps-docs-check distclean docs docs-canary docs-clean integration-clean test test-source test-dist test-doxygen test-doxygen-dist verify-bashdeps verify-build-deps FORCE

## Prepare dependencies, validate generated artifacts, and produce all checksums.
all: deps
	$(MAKE) --no-print-directory test-dist checksums

## Build the development, ordinary, and minified consumer artifacts offline.
build: verify-build-deps $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	@header() { \
		artifact=$$1; transformation=$$2; \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' "# Artifact: $$artifact"; \
		printf '%s\n' "# Transformation: $$transformation"; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_PYTHON_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_PYTHON_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
	}; \
	header 'development' 'none' >"$(DIST_DEV_FILTER).tmp"; \
	tail -n +2 "$(SOURCE_FILTER)" >>"$(DIST_DEV_FILTER).tmp"; \
	header 'ordinary' 'full-line comments removed' >"$(DIST_FILTER).tmp"; \
	tail -n +2 "$(SOURCE_FILTER)" | sed '/^[[:space:]]*#/d' >>"$(DIST_FILTER).tmp"; \
	header 'minified' 'AWK Minifier v$(AWK_MINIFIER_VERSION)' >"$(DIST_MIN_FILTER).tmp"; \
	tail -n +2 "$(SOURCE_FILTER)" | sed '/^[[:space:]]*#/d' | "$(AWK_BIN)" -f "$(AWK_MINIFIER)" >>"$(DIST_MIN_FILTER).tmp"; \
	for artifact in "$(DIST_DEV_FILTER)" "$(DIST_FILTER)" "$(DIST_MIN_FILTER)"; do \
		chmod 0755 "$$artifact.tmp"; \
		mv "$$artifact.tmp" "$$artifact"; \
	done

## Run GNU awk lint against maintained root AWK sources.
check:
	@command -v gawk >/dev/null 2>&1 || { printf '%s\n' 'gawk is required for make check' >&2; exit 1; }
	@for source in $(AWK_SOURCES); do \
		printf '%s\n' "Linting $$source"; \
		gawk --lint=fatal -f "$$source" </dev/null >/dev/null; \
	done

## Run one TAP stream covering maintained source and every generated artifact.
test: build
	AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh \
		"source=$(SOURCE_FILTER)" \
		"dev=$(DIST_DEV_FILTER)" \
		"dist=$(DIST_FILTER)" \
		"min=$(DIST_MIN_FILTER)"

## Run the TAP semantic regression suite against the maintained source file.
test-source:
	AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh "source=$(SOURCE_FILTER)"

## Build and run the TAP semantic suite against all generated artifacts.
test-dist: build
	@for artifact in $(DIST_FILTERS); do \
		test "$$(head -n 1 "$$artifact")" = '#!/usr/bin/awk -f'; \
		grep -Fxq '# Generated by make build. Do not edit directly.' "$$artifact"; \
		grep -Fxq '# Source files: $(SOURCE_FILTER)' "$$artifact"; \
		grep -Fxq '# DOXYGEN_PYTHON_VERSION=$(VERSION)' "$$artifact"; \
		grep -Fxq '# DOXYGEN_PYTHON_BUILD_DATE=$(BUILD_DATE)' "$$artifact"; \
		grep -Fxq '# DOXYGEN_PYTHON_BUILD_COMMIT=$(BUILD_COMMIT)' "$$artifact"; \
	done
	AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh \
		"dev=$(DIST_DEV_FILTER)" \
		"dist=$(DIST_FILTER)" \
		"min=$(DIST_MIN_FILTER)"

## Exercise governed Python fixtures through Doxygen with the selected filter.
test-doxygen:
	@test -f "$(DOXYGEN_PYTHON_FILTER)" || { printf '%s\n' 'Missing Python Doxygen filter' >&2; exit 1; }
	@command -v doxygen >/dev/null 2>&1 || { printf '%s\n' 'doxygen is required for make test-doxygen' >&2; exit 1; }
	$(MAKE) --no-print-directory integration-clean
	AWK_BIN="$(AWK_BIN)" DOXYGEN_PYTHON_FILTER="$(abspath $(DOXYGEN_PYTHON_FILTER))" doxygen "$(INTEGRATION_CONFIG)"
	grep -R -q 'Normalize a supplied value' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Value to normalize' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'The canonical normalized value' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'ValueError' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Track lifecycle status for one operation' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Return the current lifecycle status' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Windows path to normalize' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'The normalized Windows path' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<title>Yields</title>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'description continues' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'before the source is exhausted' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'description also continues' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<title>Type of path</title>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'pathlib.Path' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<title>Return type</title>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Configuration' "$(INTEGRATION_OUT)/xml"

## Exercise every generated release candidate through Doxygen.
test-doxygen-dist: build
	@for artifact in $(DIST_FILTERS); do \
		printf '%s\n' "Doxygen integration: $$artifact"; \
		$(MAKE) --no-print-directory test-doxygen AWK_BIN="$(AWK_BIN)" DOXYGEN_PYTHON_FILTER="$$artifact"; \
	done

## Generate SHA-256 checksums for every generated artifact.
checksums: build $(DIST_CHECKSUMS)

$(DIST_DIR)/%.awk.sha256: $(DIST_DIR)/%.awk
	cd "$(DIST_DIR)" && sha256sum "$(notdir $<)" >"$(notdir $@)"

FORCE:

## Bootstrap only bashdeps directly, verifying pinned bytes before execution.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ]; \
		else \
			return 2; \
		fi; \
	}; \
	if [ -f "$@" ] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then \
		curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	elif command -v wget >/dev/null 2>&1; then \
		wget -qO "$$tmp" "$(BASHDEPS_URL)"; \
	else \
		printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; \
	fi; \
	verify_hash "$$tmp" || { printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; }; \
	chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

## Verify the pinned bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable vendor/bashdeps.bash; run make deps or make deps-docs' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	elif command -v shasum >/dev/null 2>&1; then \
		[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; \
	fi

## Synchronize build dependencies; this target may use the network.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify prepared build dependencies without network access or repair.
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

## Require prepared, pinned build dependencies without network access.
verify-build-deps: deps-check
	@test -r "$(AWK_MINIFIER)" || { printf '%s\n' 'Missing build dependency vendor/awk-minifier.awk; run make deps' >&2; exit 1; }

## Synchronize documentation-only dependencies; this target may use the network.
deps-docs: $(BASHDEPS) $(DOCS_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DOCS_MANIFEST)"

## Verify prepared documentation dependencies without network access or repair.
deps-docs-check: verify-bashdeps $(DOCS_MANIFEST)
	"$(BASHDEPS)" verify "$(DOCS_MANIFEST)"

## Generate the ephemeral ADR landing page from maintained framing and ADR source.
adr-index:
	@test -r "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps-docs first' >&2; exit 1; }
	@test -r "$(ADR_INDEX_INTRO)" || { printf '%s\n' 'Missing ADR landing-page introduction' >&2; exit 1; }
	@test -r "$(ADR_INDEX_OUTRO)" || { printf '%s\n' 'Missing ADR landing-page conclusion' >&2; exit 1; }
	@tmp="$(ADR_INDEX_FILE).tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" -o "$(ADR_INDEX_OUTRO)" >"$$tmp"; \
	mv "$$tmp" "$(ADR_INDEX_FILE)"; \
	trap - EXIT

## Generate stable reference documentation with bashdeps-pinned released filters.
docs: deps-docs-check
	$(MAKE) --no-print-directory docs-canary \
		AWK_DOXYGEN_FILTER="$(VENDOR_AWK_FILTER)" \
		BASH_DOXYGEN_FILTER="$(VENDOR_BASH_FILTER)"

## Generate reference documentation with explicitly selected filter paths.
docs-canary:
	@test -f "$(AWK_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing AWK Doxygen filter' >&2; exit 1; }
	@test -f "$(BASH_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing Bash Doxygen filter' >&2; exit 1; }
	chmod 0755 "$(AWK_DOXYGEN_FILTER)" "$(BASH_DOXYGEN_FILTER)"
	"$(AWK_BIN)" -f "$(AWK_DOXYGEN_FILTER)" -- --strict --compact "$(SOURCE_FILTER)" >/dev/null
	awk -f "$(BASH_DOXYGEN_FILTER)" -- --strict --compact ./tests/run-tests.sh >/dev/null
	$(MAKE) --no-print-directory adr-index
	$(MAKE) --no-print-directory docs-clean
	AWK_DOXYGEN_FILTER="$(abspath $(AWK_DOXYGEN_FILTER))" \
	BASH_DOXYGEN_FILTER="$(abspath $(BASH_DOXYGEN_FILTER))" \
		doxygen Doxyfile

## Remove generated Python/Doxygen integration output.
integration-clean:
	rm -rf "$(INTEGRATION_OUT)"

## Remove generated project reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

clean: integration-clean docs-clean
	rm -rf "$(DIST_DIR)"

## Remove all generated build, reference, ADR-navigation, and dependency state.
distclean: clean
	rm -rf "$(VENDOR_DIR)"
	rm -f "$(ADR_INDEX_FILE)"
